(require 'package)

(defvar marmalade '("marmalade" . "http://marmalade-repo.org/packages/"))
(defvar gnu '("gnu" . "http://elpa.gnu.org/packages/"))
(defvar melpa '("melpa" . "http://melpa.milkbox.net/packages/"))

;; Add marmalade to package repos
(add-to-list 'package-archives marmalade t)
(add-to-list 'package-archives melpa t)

(defun packages-install (&rest packages)
  (mapc (lambda (package)
          (let ((name (car package))
                (repo (cdr package)))
            (when (not (package-installed-p name))
              (let ((package-archives (list repo)))
                (package-install name)))))
        packages)
  (delete-other-windows))

(setq packages-in-use '((cons 'auto-complete marmalade)
	  (cons 'auto-complete-clang marmalade)
	  (cons 'autopair marmalade)
	  (cons 'bm marmalade)
	  (cons 'color-theme-sanityinc-tomorrow marmalade)
	  (cons 'deft marmalade)
	  (cons 'escreen marmalade)
	  (cons 'etags-table marmalade)
	  (cons 'expand-region marmalade)
	  (cons 'helm marmalade)
	  (cons 'helm-gtags marmalade)
	  (cons 'highlight-parentheses marmalade)
	  (cons 'highlight-symbol marmalade)
	  (cons 'hungry-delete marmalade)
	  (cons 'idle-highlight-mode marmalade)
	  (cons 'iedit marmalade)
	  (cons 'js2-mode marmalade)
	  (cons 'magit marmalade)
	  (cons 'mark-multiple marmalade)
	  (cons 'popup marmalade)
	  (cons 'rainbow-delimiters marmalade)
	  (cons 'rainbow-mode marmalade)
	  (cons 'rsense marmalade)
	  (cons 'ruby-block marmalade)
	  (cons 'ruby-electric marmalade)
	  (cons 'ruby-tools marmalade) 
	  (cons 'smex marmalade)
	  (cons 'sunrise-commander marmalade)
	  (cons 'textmate marmalade)
	  (cons 'wrap-region marmalade)
	  (cons 'yasnippet marmalade)))
