
(load "torment-package")
(load "torment-utilities")
(load "torment-general")
(load "torment-os")
(load "torment-autocomplete")
(load "torment-helm")
(load "torment-git")
(load "torment-html")
(load "torment-java")
(load "torment-scala")
(load "torment-xml")
(load "torment-javascript")
(load "torment-css")
(load "torment-cpp")
(load "torment-csharp")
(load "torment-objc")
(load "torment-ruby")
(load "torment-lisp")
(load "torment-powershell")
(load "torment-notes")
(load "torment-file")
(load "torment-gnus")
(load "torment-tramp")
;;(load "torment-dict")

(setq magit-last-seen-setup-instructions "1.4.0")
