
(load "torment-utilities")
(load "torment-general")
(load "torment-os")
(load "torment-autocomplete")
(load "torment-helm")
(load "torment-git")
(load "torment-xml")
(load "torment-javascript")
(load "torment-css")
(load "torment-cpp")
(load "torment-objc")
(load "torment-ruby")
(load "torment-lisp")
(load "torment-notes")
(load "torment-file-management")
